### ISSUE TITLE
Only seeing unknown in Device Name column

### ISSUE THREAD

**Issue by scauer** [starsy/Karabiner-Elements#2]
Thanks for this, I really looking forward to getting this to work.

I'm not seeing anything in the "Device Name" column except for "UNKNOWN" and only "Not Specified" in the "Vendor\Product ID" column.

![karabiner-elements_preferences_and_alfred_preferences_and_inindca___architect___hackathon-debug_ _bitbucket](https://user-images.githubusercontent.com/1231465/27035191-6b5de61a-4f4e-11e7-9dfb-c70b7a526326.png)

I do have devices in the "Devices" tab.
![karabiner-elements_preferences_and_alfred_preferences_and_inindca___architect___hackathon-debug_ _bitbucket](https://user-images.githubusercontent.com/1231465/27035216-8a898e40-4f4e-11e7-86ef-6c46c952495b.png)

**Comment by scauer** [comment]
Looks like once I undocked my MacBook and redocked the entries became available, although "Device Name" shows a black, but selected, entry and it all appears to be working correctly.

Thanks for this.

**Comment by starsy** [comment]
@scauer Glad you found it useful and made it work. 

I will go through the flow again to see how the devices are discovered and added into the profile. The device name should not be blank, there must be something wrong.

**Comment by starsy** [comment]
@scauer Issue fixed, now it supports identifying the connected devices and their names on-the-fly. Download here: https://github.com/starsy/Karabiner-Elements/releases/latest

You need to do 'rm -f  ~/.config/karabiner/karabiner2.json'  or manually remove the "devices" section in karabiner2.json to make the device name right.

Please let me know whether it works for you.

**Comment by scauer** [comment]
It works perfectly now. Thanks.
